baseURL = 'https://michaelpeterhartmann.net/'
languageCode = 'en-us'
title = 'Michael Peter Hartmann'
theme = 'mike-theme'
enableRobotsTXT = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[build]
  [build.buildStats]
    enable = true
[security]
  enableInlineShortcodes = true
